(eq? (evaluate "test/programs/1") 150)
(eq? (evaluate "test/programs/2") -4)
(eq? (evaluate "test/programs/3") 10)
(eq? (evaluate "test/programs/4") 16)
(eq? (evaluate "test/programs/5") 220)
(eq? (evaluate "test/programs/6") 5)
(eq? (evaluate "test/programs/7") 6)
(eq? (evaluate "test/programs/8") 10)
(eq? (evaluate "test/programs/9") 5)
(eq? (evaluate "test/programs/10") -39)
;(evaluate "test/programs/11")
;(evaluate "test/programs/12")
;(evaluate "test/programs/13")
;(evaluate "test/programs/14")
(parser "test/programs/15")
(eq? (evaluate "test/programs/15") 'true)